
            <div class="innerpages_sub">
              <div class="innerpage_txt"> <strong>Mailing Address Rental Agreement</strong>
              	<ul>
   <li>1. This Mailing Address Rental Agreement is made and entered into by the customer identified above ("Customer") for the use of and services related to a mailbox (the "Mailbox") and for mail forwarding services by International Mail Forwarding Network identified above ("IMFN") and an affiliated business center identified above (the "Center") under the terms set forth herein.</li>
   <li>2. The Customer mandates IMFN to rent a mailbox in a Center located in the city chosen by the Customer and to ensure the management of the rental agreement and, if necessary, the follow-up of mail forwarding services according to Customer's instructions.</li>
   <li>3. Customer agrees that Customer will not use the Center premises or any Center services for any unlawful, illegitimate or fraudulent purpose or for any purpose prohibited by U.S. postal regulations or those of the country where the Center is located. Customer further agrees that any use of the Mailbox shall be in conformity with all applicable federal, state, provincial and local laws.</li>
   <li>4. In the case of a mailbox rented in the United States, each individual or entity must sign a separate U.S. Postal Service Form 1583 ("Form 1583") to be authorized to receive mail or packages at the Mailbox. However, spouses may complete one Form 1583, as long as both spouses include their separate information on the Form.</li>
   <li>5. This Agreement and Form 1583 shall remain confidential, except that this Agreement and Form 1583 may be disclosed upon request of any law enforcement or other governmental agency, or when legally mandated. Additionally, Customer acknowledges that pursuant to postal regulations the information required to complete Form 1583 may be made available by the U.S. Postal Service to the public if "yes" in block five (5) on Form 1583 is checked. Upon request, Customer agrees to complete all necessary documents, including Form 1583 and any required acknowledgement form relating to service of process. Customer further agrees to sign an updated version of this Agreement and Form 1583 upon request., and this form must be notarized.</li>
   <li>6. Possession of the Mailbox key shall be considered valid evidence that the possessor is duly authorized to remove any contents from the Mailbox. In the event of death or incapacity of Customer, the Center will require the appropriate documents from the Probate Court, the executor of the estate, the trustee or other similar person or entity before releasing mail or packages to a requesting party.</li>
   <li>7. If a Customer wishes to dispose the Customer to pick up the mail himself at the Center, the Customer must pay a refundable security/key deposit in the amount of $25</li>
   <li>8. The Customer must pay in advance all applicable rental fees according to the category of the city chosen by Customer and the duration of Customer's rental agreement. The security/key deposit is refundable upon expiration, cancellation or termination of this Agreement, provided that Customer returns the key, key card and/or other similar device, and pays all sums owed to the Center. Mailbox service fees are all due and payable in advance and Customer agrees that the Center may hold mail and packages pending payment. There will be no proportions or refunds for cancellation of any service. Customer agrees to pay a late fee of $10 per day if any payment is not received within five (5) days of when due. In the event the Mailbox lock is changed upon the request or fault of Customer, Customer agrees to pay a fee of $25. Mailbox service fees and other related fees stated herein are subject to change. In the event that Customer receives an unreasonable volume of mail or packages at the Mailbox according to the Center's reasonable judgement, the Center may require Customer to upgrade to a larger size mailbox and pay any additional charge. The Center reserves the right to increase the Mailbox service fees in the event that Customer adds additional individuals or entities to the names of those individuals or entities authorized to receive mail and packages at the Mailbox pursuant to Form 1583.</li>
   <li>9. In the event that Customer wishes for his mail to be forwarded, Customer must pay applicable deposit according to type of service (AirMail or Express Service by commercial courier service) and the frequency chosen by Customer.</li>
  <li>10. Each time mail is forwarded, Customer agrees to pay handling charges of $9 (minimum to see the Mail Forwarding Fee Chart) plus applicable transportation fees according to the type of service chosen by Customer.</li>
  <li>11. During rental period, Customer can change his mail forwarding address. In this event, Customer must inform IMFN of any change in forwarding address at least fifteen (15) days in advance. For any change in mail forwarding address, Customer agrees to pay administrative fees of $20, which will be deducted from deposit paid for mail forwarding.</li>
  <li>12. At the end of rental period, IMFN will reimburse Customer for the part of deposit related to mail forwarding paid by Customer and which will not have been used. In this event, within a delay of 6 to 8 weeks from the end of rental period, IMFN will send Customer a check for the part that has not been used from deposit paid initially by Customer as well as a Statement of Account. The delay of 6 to 8 weeks is to ensure that mail arriving after the end of the Agreement will be forwarded.</li>
  <li>13. Upon expiration, cancellation or termination of this Agreement, the Center will:</li>
  <ul>
         <li>1. Re-mail (i.e. forward) Customer's mail for one (1) month, provided Customer pays the postage, packaging material, and forwarding fees in advance. Additionally, Customer must pay a monthly storage fee of $50 for the period of time during which mail is forwarded. It is Customer's responsibility to make arrangements with the Center to identify any mail forwarding needs prior to the expiration, cancellation or termination of this Agreement. The Customer agrees that his/her failure to prepay and set up mail storage and forwarding prior to the end of the mail receiving Agreement will automatically convey his/her desire not to forward and/or store their mail, and authorizes the Center to discard and/or destroy ALL mail received after the mail receiving Agreement expiration date.</li>
         <li>2. Discard or destroy any "Unsolicited Mail" (e.g., bulk mail; mail addressed as "occupant", "current resident" or similar designations; or coupons, advertising or other promotional material) delivered to or remaining at the Center.</li>
         <li>3. Retain Customer's mail, other than Unsolicited Mail, at the Center for a period of thirty (30) days from the date of expiration, cancellation or termination of this Agreement, whichever comes first, if Customer leaves no forwarding fees or forwarding address. After such time, any mail or package may be discarded or destroyed. In order to pick up any mail or package during the thirty (30) days, Customer must pay a storage fee of $50 U.S. for the period during which the Center holds the mail or package(s), plus a service fee of $9 for each time Customer visits the Center to pick such items.</li>
         <li>4. Refuse any package addressed to Customer delivered by any party other that the U.S. Postal Service, such as a commercial courier service.</li>
  </ul>         
  <li>14. One (1) month after the expiration, cancellation or termination of this Agreement, the Center may:</li>
  <ul>
         <li>1. Refuse any mail or package addressed to Customer and delivered to the Center.</li>
         <li>2. Discard or destroy any of the Customer's mail or package delivered to or remaining at the Center at such time.</li>
  </ul>         
  <li>15. The term of this Agreement shall be the initial period paid for by Customer and any renewal period paid for by Customer from time to time. Renewal of this Agreement for additional terms shall be at the Center's sole discretion.</li>
  <li>16. Customer agrees that the Center may terminate or cancel this Agreement for good cause at any time by providing Customer fifteen (15) days written notice. Good cause shall include but is not limited to: 1) Customer abandons the Mailbox; 2) Customer uses the Mailbox for unlawful, illegitimate or fraudulent purposes; 3) Customer fails to pay monies owed the Center when due; 4) Customer receives an unreasonable volume of mail or packages; 5) Customer engages in offensive, abusive or disruptive behavior toward other customers or the Center of the Center's employees; and 6) Customer violates any provision of this Agreement. Customer acknowledges that, for the purpose of determining good cause for termination of this Agreement as provided herein, the actions of any person authorized by Customer to use the Mailbox will be attributed to Customer.</li>
  <li>17. Any written notice to Customer required or permitted under this Agreement shall be deemed delivered twenty-four (24) hours after placement of such notice in Customer's Mailbox or at the time personally delivered to Customer. In the event of a termination notice based upon abandonment of the Mailbox, notice shall be deemed delivered (a) on the next day after placing in the hands of a commercial courier service or the United States postal Service for next day delivery, or (b) five (5) days after placement in the United States Mail by Certified Mail, Return Receipt Requested, postage prepaid, and addressed to Customer at Customer's address as set forth in Form 1583, or on the date of actual receipt, whichever is earlier.</li>
  <li>18. As Customer's authorized agent for receipt of mail, the Center will accept all mail, including registered, insured and certified items. Unless prior arrangements have been made, the Center shall only be obligated to accept mail, or packages delivered by commercial courier services which require a signature from the Center as a condition of delivery. Customer must accept and sign for all mail and packages upon the request of the Center. Packages not picked up or forwarded within prescribed delay as stipulated in Forwarding Agreement will be subject to a storage fee of $10 per day per package that must be paid before Customer can receive package. In the event Customer refuses to accept any mail or package, the Center may return the mail or package to the sender and Customer will be responsible for any postage or other fees associated with such return. C.O.D. items will be accepted ONLY if prior arrangements have been made and payment in advance is provided to the Center.</li>
  <li>19. Customer agrees to protect, indemnify, defend and hold harmless IMFN, the Center and their respective affiliates, subsidiaries, parent corporations, franchisees, officers, directors, agents and employees from and against any and all losses, damages, expenses, claims, demands, liabilities, judgments, settlement amounts, costs and causes of action of every type and character arising out of or in connection with the use or possession of the Mailbox, including without limitation, any demands, claims and causes of action for personal injury or property damage arising from such use or possession, from failure of the U.S. Postal Service or any commercial courier service to deliver on time or otherwise deliver any items (mail, packages, etc.) from damage to or loss of any package or mail, or to the Mailbox contents by any cause whatsoever, and from any violation by Customer of applicable federal, state or local laws.</li>
  <li>20. Customer acknowledges and agrees that the Center is an independent member of IMFN and that IMFN is not responsible for any acts or omissions of its franchisees.</li>
  <li>21. CUSTOMER HEREIN AGREES THAT THE TOTAL AMOUNT OF LIABILITY OF THE CENTER AND OF IMFN, IF ANY, FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED $100 REGARDLESS OF THE NATURE OF THE CLAIM.</li>
  <li>22. Customer must use the exact mailing address for the Mailbox without modification as set forth by IMFN. Mail received by Customer must bear a delivery address that contains at least the following elements, in this order:</li>
  <ul>
         <li>1. Intended addressee's name or other identification. Examples: Joe Doe or ABC Co.</li>
         <li>2. "#" and number. Example: # 234.</li>
         <li>3. Street number and name of post office box number or rural route designation and number. Examples: 10 Main Street.</li>
         <li>4. City, state, and ZIP Code (5-digit or ZIP+4). Example: Herndon, VA 22071-2716.</li>
      	 <li>The Postal Service will return mail without a proper address to the sender endorsed "Undeliverable as Addressed."</li>
  </ul>
  <li>23. Delivery by commercial courier services must be made to the Center street address only (and not to a P.O. Box). "P.O. Box" may be used only if it is part of Customer's "Caller Service" (arrangement for delivery of mail through Centers using a U.S. Postal Service address) address format. In such case, the "#" designation must also be used. Upon signing this Agreement, Customer shall provide two forms of valid identification, one of which shall include a photograph. This Agreement may not be amended or modified, except in writing signed by both parties.</li>
  <li>24. Payment by credit card are subject to an additional Fee of 5% to cover the bank fee and other fees.</li>
  <li>25. Renewal of Rental Agreement. One (1) month prior to the end of the rental agreement, a notice of renewal will be sent to the Customer by e-mail. Customer will be required to inform IMFN, by e-mail, of his decision to renew or not to renew  the rental agreement before the end of the Agreement. If the Customer does not inform IMFN of his/her intention to not renew his/her rental agreement before the expiry of said agreement, the rental of the business address will be automatically renewed according to the terms of the initial Agreement.</li>
              	
              	</ul>
              </div>
            </div>

 